
<<setup, include=FALSE>>=
knit_hooks$set(document=function(x){
		 x <- sub('\\usepackage{framed}', '', x, fixed=TRUE) 
		 sub('\\usepackage[]{color}', '\\usepackage{xcolor}', x, fixed = TRUE)
})
opts_chunk$set(
	       echo=FALSE 
	       , message=FALSE
	       , warning=FALSE
	       , results="hide"
	       , fig.show='hold'
	       , fig.width=6
	       , fig.height=6
	       , fig.align="center"
	       , dev="tikz"
       )
options(scipen=3, digits=4)
@ 

